### ISSUE TITLE
Python3.5: unsupported operand type(s) for +: 'dict_items' and 'dict_items

### ISSUE THREAD

**Issue by gitiup** [burke-software/django-admin-export#8] opened 2016-01-20 20:04 UTC
This is what I get using django 1.9 and Python 3.5.

Any idea?

**Comment by bufke** [comment] 2016-02-13 15:30
Duplicate of #6

**Closed by bufke** 2016-02-13 15:30 UTC

**Comment by bufke** [comment] 2016-02-13 15:33
I put up a notice on the README about looking for a new maintainer. Let me know if you think you could help.
